#

usage:
	@echo "usage: make run | run-mqtt"

all::
clean::;	rm -f *~

run:
#	@echo "compute 12 + 34 = 46"
#	@scxmlrun calc.scxml calc.in -o /dev/null
	shelltest calc.conf

run-mqtt:
	shelltest calc_mqtt.conf
