#

usage:
	@echo "usage: make <target>"
	@echo "where <target> can be either of the following"
	@echo -e "\ttest\trun tests"

test::
	$(MAKE) -C ecmascript -j8 $@

all::
clean::
	$(MAKE) -C ecmascript $@
install::
