#

usage:
	@echo "usage: make launch|build|test"

PROJECT_DIR	= .
#CONTRACTS	= $(shell echo contracts/*.sol)
CONTRACTS	= contracts/Ballot.sol
#TESTS		= $(shell echo scenarios/*.js)
TESTS		= scenarios/ballot_test.js
GAS_LIMIT	= "8000000"

include ../Makefile.truffle
